const test = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const Pharmacy = require('../models/Pharmacy');
const User = require('../models/User');
const routes = require('../routes/pharmacyRoutes');
test('HTTP inventory CRUD, owner isolation, role security, search and validation', async t => {
  const oldSecret = process.env.JWT_SECRET; process.env.JWT_SECRET = 'pharmacy-test-secret';
  t.after(() => { if (oldSecret === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = oldSecret; });
  const owner = new mongoose.Types.ObjectId(), other = new mongoose.Types.ObjectId(), customer = new mongoose.Types.ObjectId();
  const p = new Pharmacy({ owner, name: 'City', address: 'Colombo', district: 'Colombo', phone: '0111234567', latitude: 6.9271, longitude: 79.8612 });
  let saves = 0;
  p.save = async () => { await p.validate(); saves++; return p; };
  t.mock.method(Pharmacy, 'findById', async id => String(id) === String(p._id) ? p : null);
  t.mock.method(Pharmacy, 'find', () => ({ lean: async () => [p.toObject()] }));
  t.mock.method(User, 'findById', id => ({ select: async () => ({ _id: id, role: String(id) === String(customer) ? 'customer' : 'pharmacy_owner' }) }));
  const app = express(); app.use(express.json()); app.use('/pharmacies', routes);
  const server = await new Promise(resolve => { const listener = app.listen(0, '127.0.0.1', () => resolve(listener)); });
  t.after(() => new Promise(resolve => server.close(resolve)));
  const request = async (url, method = 'GET', user, body) => {
    const response = await fetch(`http://127.0.0.1:${server.address().port}/pharmacies${url}`, { method, headers: { 'Content-Type': 'application/json', ...(user ? { Authorization: `Bearer ${jwt.sign({ userId: user }, process.env.JWT_SECRET)}` } : {}) }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
    return { status: response.status, data: await response.json() };
  };
  const path = `/${p._id}/inventory`;
  assert.equal((await request(path, 'POST', undefined, {})).status, 401);
  assert.equal((await request(path, 'POST', customer, {})).status, 403);
  assert.equal((await request(path, 'POST', other, {})).status, 403);
  assert.equal((await request(`/${p._id}`, 'PUT', other, { name: 'Steal' })).status, 403);
  assert.equal((await request(`/${p._id}`, 'DELETE', other)).status, 403);
  assert.equal((await request(path, 'POST', owner, { name: 'Panadol', quantity: -1 })).status, 400);
  assert.equal((await request(path, 'POST', owner, { name: 'Panadol', quantity: 1, price: -1 })).status, 400);
  assert.equal((await request(path, 'POST', owner, { name: 'Panadol', quantity: 1, imageUrl: 'javascript:alert(1)' })).status, 400);
  assert.equal(saves, 0);
  const added = await request(path, 'POST', owner, { name: 'Panadol', quantity: 25, price: 120, imageUrl: 'https://images.example.test/panadol.png' });
  assert.equal(added.status, 201); const medicineId = added.data.inventory[0]._id;
  assert.equal((await request(path, 'GET', owner)).data.inventory.length, 1);
  assert.equal((await request('/search?medicine=pAnAd')).data.pharmacies.length, 1);
  const detail = (await request(`/${p._id}?lat=6.9271&lng=79.8612`, 'GET', customer)).data.pharmacy;
  assert.equal(detail.distance, 0);
  assert.equal(detail.medicines[0].quantity, 25);
  assert.equal(detail.medicines[0].price, 120);
  assert.equal(detail.medicines[0].imageUrl, 'https://images.example.test/panadol.png');
  assert.equal((await request(`/${p._id}?lat=no&lng=1`)).status, 400);
  assert.equal((await request(`${path}/${medicineId}`, 'PATCH', other, { quantity: 0 })).status, 403);
  assert.equal((await request(`${path}/${medicineId}`, 'PATCH', customer, { quantity: 0 })).status, 403);
  assert.equal((await request(`${path}/${medicineId}`, 'PATCH', owner, { quantity: 0 })).status, 200);
  assert.equal((await request(`/${p._id}`)).data.pharmacy.medicines[0].availability, 'Out of Stock');
  assert.equal((await request('/search?medicine=Panadol')).data.pharmacies.length, 0);
  assert.equal((await request(`${path}/${medicineId}`, 'PATCH', owner, { name: 'Panadol Extra', quantity: 3, price: null, imageUrl: '' })).status, 200);
  assert.equal(p.inventory[0].imageUrl, '');
  assert.equal((await request(`/${p._id}`)).data.pharmacy.medicines[0].availability, 'Available');
  assert.equal(p.inventory[0].price, undefined);
  assert.equal((await request(`${path}/${medicineId}`, 'DELETE', owner)).status, 200);
  assert.equal(p.inventory.length, 0);
  assert.equal((await request('/search?lat=abc&lng=1')).status, 400);
  assert.equal((await request(`/${p._id}/hours`, 'PUT', other, {})).status, 403);
  const openingHours = Array.from({ length: 7 }, (_, day) => ({ day, closed: false, allDay: true }));
  assert.equal((await request(`/${p._id}/hours`, 'PUT', owner, { openingHours, timezone: 'Asia/Colombo' })).status, 200);
  assert.equal((await request('/search?hour24=true&emergency=true')).data.pharmacies.length, 1);
  const publicResult = (await request(`/${p._id}`)).data.pharmacy;
  assert.equal(publicResult.owner, undefined); assert.equal(publicResult.inventory, undefined);
  p.owner = undefined;
  assert.equal((await request(path, 'POST', owner, { name: 'Panadol', quantity: 1 })).status, 403);
});
